apiVersion: v1
kind: Namespace
metadata:
  name: avi-nestjs
  labels:
    name: avi-nestjs

---
apiVersion: v1
kind: Pod
metadata:
  name: nestjs
  labels:
    run: nestjs
  namespace: avi-nestjs
spec:
  containers:
    - name: nest-cloud-run
      image: nest-cloud-run:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-hello-world-deployment
  namespace: avi-nestjs
  labels:
    app: nestjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs
  template:
    metadata:
      labels:
        app: nestjs
    spec:
      containers:
        - name: nest-cloud-run
          image: nest-cloud-run:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: nestjs-hello-world-service
  namespace: avi-nestjs
spec:
  selector:
    app: nestjs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
